/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return current session state */
        get: operations["getSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/itineraries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listItineraries"];
        put?: never;
        post: operations["createItinerary"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/itineraries/{itineraryId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                itineraryId: components["parameters"]["ItineraryId"];
            };
            cookie?: never;
        };
        get: operations["getItinerary"];
        put: operations["updateItinerary"];
        /** @description Multipart-compatible method-override endpoint. `_method=PUT` is accepted; POST also updates. */
        post: operations["updateItineraryMultipart"];
        delete: operations["deleteItinerary"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/itineraries/{itineraryId}/files/{fileId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                itineraryId: components["parameters"]["ItineraryId"];
                fileId: number;
            };
            cookie?: never;
        };
        get: operations["getItineraryFile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/packing-templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listPackingTemplates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/itineraries/{itineraryId}/members": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                itineraryId: components["parameters"]["ItineraryId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["addMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/itineraries/{itineraryId}/members/{memberId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                itineraryId: components["parameters"]["ItineraryId"];
                memberId: number;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["removeMember"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/itineraries/{itineraryId}/shared-access": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                itineraryId: components["parameters"]["ItineraryId"];
            };
            cookie?: never;
        };
        get: operations["getSharedAccessStatus"];
        put?: never;
        post: operations["verifySharedAccess"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/itineraries/{itineraryId}/viewer-share": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                itineraryId: components["parameters"]["ItineraryId"];
            };
            cookie?: never;
        };
        get?: never;
        put: operations["setViewerShare"];
        post?: never;
        delete: operations["revokeViewerShare"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Session: {
            authenticated: boolean;
            user: null | {
                id: number;
                name: string;
                /** Format: email */
                email: string;
            };
            auth_error: string | null;
        };
        ItinerarySummary: {
            /** Format: uuid */
            id: string;
            title: string;
            overview_text: string | null;
            /** Format: date-time */
            created_at: string | null;
            /** Format: date-time */
            updated_at: string | null;
            permissions: {
                can_edit: boolean;
                can_delete: boolean;
            };
        };
        ItinerarySave: {
            title: string;
            overview_text: string | null;
            template_type: string | null;
            plans: {
                /** @description Existing plan row ID */
                id?: number;
                client_id: string;
                /** Format: date */
                date?: string | null;
                time?: string | null;
                title?: string | null;
                content?: string | null;
                order: number;
                /** @description Exact attachment IDs to keep. */
                existing_file_ids: number[];
            }[];
            packing_items: {
                /** @description Existing caller-owned row ID */
                id?: number;
                name: string | null;
                is_checked: boolean;
                order: number;
            }[];
            souvenirs: {
                /** @description Existing row ID */
                id?: number;
                name: string | null;
                is_checked: boolean;
                order: number;
            }[];
            notes: {
                /** @description Existing row ID */
                id?: number;
                title: string | null;
                text: string | null;
                order: number;
            }[];
            /** @description Optional on create only; confirmed by the matching confirmation field. */
            shared_password?: string;
            shared_password_confirmation?: string;
            /** Format: date-time */
            viewer_share_expires_at?: string | null;
        };
        Itinerary: {
            /** Format: uuid */
            id: string;
            title: string;
            overview_text: string | null;
            template_type: string | null;
            plans: {
                id: number;
                /** Format: date */
                date: string | null;
                time: string | null;
                title: string | null;
                content: string | null;
                order: number;
                files: {
                    id: number;
                    file_name: string;
                    /** Format: uri-reference */
                    url: string;
                }[];
            }[];
            /** @description Only the authenticated caller's personal list; empty for shared viewers. */
            packing_items: components["schemas"]["ChecklistItem"][];
            souvenirs: components["schemas"]["ChecklistItem"][];
            notes: {
                id: number;
                title: string | null;
                text: string | null;
                order: number;
            }[];
            /** @description Member identities are included only for users allowed to manage members. */
            members: components["schemas"]["Member"][];
            permissions: {
                can_edit: boolean;
                can_delete: boolean;
                can_manage_members: boolean;
                can_manage_viewer_share: boolean;
            };
            viewer_share: {
                active: boolean;
                /**
                 * Format: date-time
                 * @description Included for the owner only.
                 */
                expires_at?: string | null;
            };
        };
        ChecklistItem: {
            id: number;
            name: string | null;
            is_checked: boolean;
            order: number;
        };
        Member: {
            id: number;
            user: {
                id: number;
                name: string;
                /** Format: email */
                email: string;
            };
            /** @enum {string} */
            role: "owner" | "member";
        };
        Error: {
            message: string;
            errors?: {
                [key: string]: string[];
            };
        };
    };
    responses: {
        /** @description Authentication required */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Authenticated user does not have the required permission */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource does not exist or is outside the itinerary scope */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Invalid request body or shared-access password */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Shared-access attempts are rate limited */
        TooManyRequests: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        ItineraryId: string;
    };
    requestBodies: {
        ItineraryMultipart: {
            content: {
                "multipart/form-data": {
                    /** @description JSON-encoded ItinerarySave object (all collections required, including empty arrays). */
                    payload: string;
                    /** @enum {string} */
                    _method?: "PUT";
                };
            };
        };
    };
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current guest or authenticated session */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
        };
    };
    listItineraries: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Itineraries owned by or shared for editing with the current user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        itineraries: components["schemas"]["ItinerarySummary"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createItinerary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["ItineraryMultipart"];
        responses: {
            /** @description Created itinerary */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Itinerary"];
                };
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["ValidationError"];
        };
    };
    getItinerary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                itineraryId: components["parameters"]["ItineraryId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Itinerary visible to the current user or shared viewer session */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Itinerary"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateItinerary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                itineraryId: components["parameters"]["ItineraryId"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["ItineraryMultipart"];
        responses: {
            /** @description Updated itinerary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Itinerary"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationError"];
        };
    };
    updateItineraryMultipart: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                itineraryId: components["parameters"]["ItineraryId"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["ItineraryMultipart"];
        responses: {
            /** @description Updated itinerary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Itinerary"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationError"];
        };
    };
    deleteItinerary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                itineraryId: components["parameters"]["ItineraryId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted itinerary */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getItineraryFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                itineraryId: components["parameters"]["ItineraryId"];
                fileId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Authorized attachment bytes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listPackingTemplates: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Existing packing checklist templates */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        templates: {
                            /** @enum {string} */
                            type: "domestic" | "overseas";
                            /** @example 国内旅行 */
                            label: string;
                            items: string[];
                        }[];
                    };
                };
            };
        };
    };
    addMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                itineraryId: components["parameters"]["ItineraryId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                };
            };
        };
        responses: {
            /** @description Member added (or already present) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        member?: components["schemas"]["Member"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationError"];
        };
    };
    removeMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                itineraryId: components["parameters"]["ItineraryId"];
                memberId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Member removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getSharedAccessStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                itineraryId: components["parameters"]["ItineraryId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Minimal metadata for the active shared itinerary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        id: string;
                        title: string;
                        /** @constant */
                        available: true;
                    };
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    verifySharedAccess: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                itineraryId: components["parameters"]["ItineraryId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    shared_password: string;
                };
            };
        };
        responses: {
            /** @description Password accepted and shared itinerary session granted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Itinerary"];
                };
            };
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationError"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    setViewerShare: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                itineraryId: components["parameters"]["ItineraryId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    shared_password?: string | null;
                    shared_password_confirmation?: string | null;
                    /** Format: date-time */
                    expires_at?: string | null;
                };
            };
        };
        responses: {
            /** @description Viewer share configured */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Itinerary"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationError"];
        };
    };
    revokeViewerShare: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                itineraryId: components["parameters"]["ItineraryId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Viewer share revoked and existing access versions invalidated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Itinerary"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
}
